---
title: "Machine Learning tutorials and R"
output: html_document
---

## Introduction

Welcome to Machine Learning tutorials with R. This is a mini-site of [kyrcha.info](http://kyrcha.info) I've created in rmarkdown to host notes on R and ML algorithms for two Data Mining courses I teach.

## Acknowledgements

The tutorials, besides including the author's original contributions and knowledge of Machine Learning algorithms and R, also include contributions from other material and more specifically: 1) from an introductory R leaflet from the Pattern Recognition course leaflets of the Electrical and Computer Engineering Department of the Aristotle University of Thessaloniki (Fall semester 2016, authors: Themistoklis Diamantopoulos/Michalis Papamichail, professor: Andreas Symeonidis), 2) the leaflet from the course CS545 Machine Learnig (Fall 2008, author and professor: Charles W. Anderson) and 3) [Software Caprentry](https://software-carpentry.org/) lessons like [Programming in R](http://swcarpentry.github.io/r-novice-inflammation/) from which the inflammation data were also included.

## License

This work is made available under the [Creative Commons Attribution license](https://creativecommons.org/licenses/by/4.0/).

## Links

- [R project](https://www.r-project.org/)
    - [R official manuals](https://cran.r-project.org/manuals.html)
    - [R packages](https://cran.r-project.org/web/packages/available_packages_by_name.html)
- [R studio](https://www.rstudio.com/) Nice R IDE that works in Linux, Mac and Windows systems.